---
# control
control:
  num_users: '8'
  assist_mode: 'stack'
  local_epoch: '1'
  global_epoch: '10'
# data
data_name: MNIST
# model
model_name: conv-linear
# experiment
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
# other
save_format: png
