---
# control
control:
  num_users: '4'
  assist_mode: 'stack'
# data
data_name: Wine
# model
model_name: linear
# experiment
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
# other
save_format: png
