---
# control
control:
  num_users: '4'
  assist_mode: 'bag'
  local_epoch: '100'
  global_epoch: '10'
# data
data_name: QSAR
# MNIST
model_name: linear
# experiment
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
