---
# control
control:
  num_users: '5'
  assist_mode: 'stacking'
  assist_rate: '1'
# data
data_name: Wine
subset: label
# model
model_name: linear
# experiment
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
# other
save_format: png
